-- CREATE TABLE Users (
--   UserID INT AUTO_INCREMENT PRIMARY KEY,
--   Username VARCHAR(50) NOT NULL,
--   Email VARCHAR(100) NOT NULL,
--   DateOfBirth DATE
-- );

-- CREATE TABLE Courses (
--   CourseID INT AUTO_INCREMENT PRIMARY KEY,
--   CourseName VARCHAR(100) NOT NULL,
--   Instructor VARCHAR(100) NOT NULL,
--   Description TEXT
-- );

-- CREATE TABLE Enrollments (
--   EnrollmentID INT AUTO_INCREMENT PRIMARY KEY,
--   UserID INT,
--   CourseID INT,
--   EnrollmentDate DATE,
--   FOREIGN KEY (UserID) REFERENCES Users(UserID),
--   FOREIGN KEY (CourseID) REFERENCES Courses(CourseID)
-- );
